[Unit]
Description=swift-cluster-status

[Service]
WorkingDirectory=/opt/exporter
#User=swift
#Group=swift
ExecStart=python3 /opt/exporter/swift-cluster-status.py /opt/exporter/etc/cluster-status.conf
Restart=always
RestartSec=10
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target
root@swft-az01-c001:~/ring/epoch16# cat /opt/exporter/etc/cluster-status.conf 
[DEFAULT]
exec_dir = /opt/swift/bin
data_dir = /opt/exporter/data
inspection_frequency = 360

bind_port = 7000
bind_ip = 100.111.0.70
